version: '3'
services:
    db:
        image: mysql
        container_name: imaster
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_USERNAME}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            # <Port exposed> : <MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:


