<?php

namespace App\Filament\Resources\PostResource\Pages;

use App\Filament\Resources\PostResource;
use App\Traits\Admin\HasCustomFormEditAction;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditPost extends EditRecord
{
    use HasCustomFormEditAction;
    protected static string $resource = PostResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
    protected function mutateFormDataBeforeFill(array $data): array
    {
      //  dd($this->record->meta->query()->where('metaable_id', 12)->with('translations')->get());
        $this->mutateData($data);
        $this->mutateMeta($data);
        return  parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        $res = parent::handleRecordUpdate($record, $data); // TODO: Change the autogenerated stub
        foreach (config('translatable.locales') as $locale) {
            $meta = $data[$locale]['meta'];
            $meta['meta_id'] = $record->meta->id;
            $meta['locale'] = $locale;
            \DB::table('meta_translations')->upsert($meta, ['meta_id', 'locale']);
        }
        return $res;
    }

}
