<?php

namespace App\Filament\Resources\SlideResource\Pages;

use App\Filament\Resources\SlideResource;
use App\Traits\Admin\HasCustomFormEditAction;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditSlide extends EditRecord
{
    protected static string $resource = SlideResource::class;
    use HasCustomFormEditAction;
    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
    protected function mutateFormDataBeforeFill(array $data): array
    {
        $this->mutateData($data);

        return  parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
}
